platform :ios, '9.0'

use_frameworks!

target 'AppShellBridge_Example' do
  pod 'AppShellBridge', :path => '../'

  react_native_path = "../../../proj/RNSample/node-modules/react-native"
  pod 'FBLazyVector', :path => "#{react_native_path}/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "#{react_native_path}/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "#{react_native_path}/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "#{react_native_path}/Libraries/TypeSafety"
  pod 'React', :path => "#{react_native_path}"
  pod 'React-Core', :path => "#{react_native_path}"
  pod 'React-Core/DevSupport', :path => "#{react_native_path}"
  pod 'React-CoreModules', :path => "#{react_native_path}/React/CoreModules"
  pod 'React-RCTActionSheet', :path => "#{react_native_path}/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', :path => "#{react_native_path}/Libraries/NativeAnimation"
  pod 'React-RCTBlob', :path => "#{react_native_path}/Libraries/Blob"
  pod 'React-RCTImage', :path => "#{react_native_path}/Libraries/Image"
  pod 'React-RCTLinking', :path => "#{react_native_path}/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', :path => "#{react_native_path}/Libraries/Network"
  pod 'React-RCTSettings', :path => "#{react_native_path}/Libraries/Settings"
  pod 'React-RCTText', :path => "#{react_native_path}/Libraries/Text"
  pod 'React-RCTVibration', :path => "#{react_native_path}/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', :path => "#{react_native_path}"

  pod 'React-cxxreact', :path => "#{react_native_path}/ReactCommon/cxxreact"
  pod 'React-jsi', :path => "#{react_native_path}/ReactCommon/jsi"
  pod 'React-jsiexecutor', :path => "#{react_native_path}/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', :path => "#{react_native_path}/ReactCommon/jsinspector"
  pod 'ReactCommon/jscallinvoker', :path => "#{react_native_path}/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "#{react_native_path}/ReactCommon"

  pod 'Yoga', :path => "#{react_native_path}/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => "#{react_native_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{react_native_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{react_native_path}/third-party-podspecs/Folly.podspec"

  target 'AppShellBridge_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
